# Generated by Django 2.1.7 on 2019-02-20 08:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.TextField(max_length=32)),
                ('phone', models.TextField(max_length=20)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('userpass', models.TextField(max_length=64)),
                ('user_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('birthday', models.DateField()),
                ('fb_access_token', models.TextField()),
                ('fb_userid', models.TextField()),
                ('lastlogin', models.DateTimeField(auto_now=True)),
                ('job', models.IntegerField()),
                ('reg_datetime', models.DateTimeField(auto_now_add=True)),
                ('session_token', models.TextField(max_length=64)),
                ('account_status', models.IntegerField()),
                ('share_code', models.TextField(max_length=10)),
                ('registration_validation_email_token', models.TextField(max_length=64)),
                ('share_ui_field', models.TextField(max_length=16)),
                ('today_sned_reset_password_mail_count', models.IntegerField()),
                ('reset_pass_token', models.TextField(max_length=64)),
                ('reset_password_datetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
