# Generated by Django 2.1.7 on 2019-02-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joystick_api', '0002_user_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='job',
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(default='1900-01-01', verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=6),
        ),
    ]
