# Generated by Django 2.1.7 on 2019-02-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joystick_api', '0003_auto_20190220_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_status',
            field=models.IntegerField(default=1),
        ),
    ]
