# Generated by Django 2.1.7 on 2019-02-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joystick_api', '0004_auto_20190220_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='today_sned_reset_password_mail_count',
            field=models.IntegerField(default=0),
        ),
    ]
