# Generated by Django 2.1.7 on 2019-02-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joystick_api', '0005_auto_20190220_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.TextField(max_length=32, verbose_name='使用者名稱'),
        ),
    ]
