# Generated by Django 2.1.7 on 2019-02-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joystick_api', '0006_auto_20190220_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.TextField(help_text='使用者名稱，只能輸入小寫英文數字', max_length=32, verbose_name='使用者名稱'),
        ),
    ]
